### ISSUE TITLE
Create PDF using extracted data

### ISSUE THREAD

**Issue by anjjunsu** [anjjunsu/unofficial-transcript-generator#31]
- [x] Create a PDF file and return it to the client as a response
- [ ] Format PDF file
    - [x] Font 
    - [x] Page size: A4
    - [x] Page Margin: Narrow
    - [x] Page number
    - [x] Title
    - [x] Student Info
    - [ ] Course Info
        - [ ] Group by Session
            - [ ] Then group by term
 - [x] Return to the client as a `Response`

**Comment by anjjunsu** [comment]
@jorido Try to read some reportLab tutorials

**Comment by anjjunsu** [comment]
[UBCTranscript_An,Junsu_63647879.pdf](https://github.com/anjjunsu/unofficial-transcript-generator/files/10322949/UBCTranscript_An.Junsu_63647879.pdf)

**2022-12-29 Current State**

**Comment by jorido** [comment]
**As of 2023-01-04**

![image](https://user-images.githubusercontent.com/84487643/210514419-8015ec3e-a8db-4229-8560-d26b4a58cadb.png)
