### ISSUE TITLE
Implement drag&drop feature for file uploading

### ISSUE THREAD

**Issue by junsu-a** [anjjunsu/unofficial-transcript-generator#38]
Hi @s1Develop! 

Please implement the drag & drop feature on the home page for file uploading.
Please feel free to use any React library.

This issue will be closed once:
- You implemented a feature
- PR is approved. (Please link your PR to this issue page)
- Please document your work 
    - On this issue, describe what have you done (very briefly)

Thanks!

**Comment by junsu-a** [comment]
[IGNORE]

**Comment by s1Develop** [comment]
Implemented Drag and Drop feature and change some code and file locations for my convenience.
