### ISSUE TITLE
Change letter grade calculation implementation

### ISSUE THREAD

**Issue by anjjunsu** [anjjunsu/unofficial-transcript-generator#60]
As @jorido suggested, tesseract OCR's letter grade recognition accuracy rate is not so great.
To resolve this issue, change the letter grade calculation implementation.

> **Before:**
> Read the letter grade on the transcript directly
>
> **After:**
> Since tesseract OCR's numerical grade recognition accuracy rate is significantly higher, read that numerical grade and calculate the letter grade

Any suggestions are welcome.

**Comment by jorido** [comment]
Can you please check whether this is a duplicate of #56? The main parsing error was due to the existing logic that handled the "-" postfix wrong.

**Comment by jorido** [comment]
> Can you please check whether this is a duplicate of #56? The main parsing error was due to the existing logic that handled the "-" postfix wrong.

@anjjunsu Please confirm this

**Comment by anjjunsu** [comment]
@jorido Thanks for the catch. Yes, it's a duplicate of #56, and confirmed it's fixed by you. 
Closing this issue
